# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspots',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
