# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20170412_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='location',
            new_name='point',
        ),
    ]
