# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20170413_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('occupied', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='point',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
