# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20170413_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='occupied',
        ),
        migrations.AddField(
            model_name='location',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
